// This file was generated by Firebase Studio
import {initializeApp, getApp, getApps} from 'firebase/app';
import {getFirestore, connectFirestoreEmulator} from 'firebase/firestore';

const firebaseConfig = {
  apiKey: "your-api-key",
  authDomain: "your-auth-domain",
  projectId: "your-project-id",
  storageBucket: "your-storage-bucket",
  messagingSenderId: "your-messaging-sender-id",
  appId: "your-app-id",
};

function createFirebaseApp(config: {}) {
  try {
    return getApp();
  } catch {
    return initializeApp(config);
  }
}

export const firebaseApp = createFirebaseApp(firebaseConfig);
export const firestore = getFirestore(firebaseApp);

if (process.env.NODE_ENV === 'development' && typeof window !== 'undefined') {
  // Point to the Firestore emulator
  // Note: this will be a no-op if the emulator is not running
  try {
    connectFirestoreEmulator(firestore, 'localhost', 8080);
    console.log('Connected to Firestore emulator');
  } catch (e) {
    console.warn('Could not connect to Firestore emulator. This is expected if you are not running it.');
  }
}
