// This file was generated by Firebase Studio
import {initializeApp, getApp, getApps} from 'firebase/app';
import {getFirestore, connectFirestoreEmulator} from 'firebase/firestore';

const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_APP_ID,
};

function createFirebaseApp(config: {}) {
  try {
    return getApp();
  } catch {
    return initializeApp(config);
  }
}

export const firebaseApp = createFirebaseApp(firebaseConfig);
export const firestore = getFirestore(firebaseApp);

if (process.env.NODE_ENV === 'development' && typeof window !== 'undefined') {
  // Point to the Firestore emulator
  // Note: this will be a no-op if the emulator is not running
  try {
    connectFirestoreEmulator(firestore, 'localhost', 8080);
    console.log('Connected to Firestore emulator');
  } catch (e) {
    console.warn('Could not connect to Firestore emulator. This is expected if you are not running it.');
  }
}
